import { useEffect, useState } from "react";
import { Menu, Image as ImageIcon, Code2, Sparkles, Brain, UserCircle2, Copy, Plus } from "lucide-react";
import DogLoader from "../components/DogLoader";
import ChatInput from "../components/ChatInput";
import { useAuth } from "../context/AuthContext";
import { useApp, type SavedMessage } from "../context/AppContext";
import type { AppPage } from "../types";
interface HomeProps{onOpenMenu:()=>void;onNavigate:(page:AppPage)=>void;onOpenAccount:()=>void;}
type Msg={role:"user"|"assistant";content:string};
function formatText(text:string){return text.split(/(```[\s\S]*?```)/g).map((part,i)=>part.startsWith("```")?<pre key={i}>{part.replace(/^```\w*\n?/,"").replace(/```$/,"\n")}</pre>:part.split(/\n\n+/).map((p,j)=><p key={`${i}-${j}`}>{p.replace(/^###\s+/gm,"").replace(/^##\s+/gm,"").replace(/^#\s+/gm,"")}</p>));}
export default function Home({onOpenMenu,onNavigate,onOpenAccount}:HomeProps){
 const {user}=useAuth(); const {memoryEnabled,activeChatId,createChat,loadMessages,saveMessage}=useApp(); const [messages,setMessages]=useState<Msg[]>([]); const [loading,setLoading]=useState(false); const [copied,setCopied]=useState<string|null>(null);
 useEffect(()=>{let cancelled=false;(async()=>{if(!activeChatId){setMessages([]);return;}const saved=await loadMessages(activeChatId);if(!cancelled)setMessages(saved.map(m=>({role:m.role,content:m.content})));})();return()=>{cancelled=true;};},[activeChatId,loadMessages]);
 const startChat=async()=>{setMessages([]);await createChat("New chat");};
 const handleSend=async(message:string)=>{let chatId=activeChatId;if(!chatId)chatId=await createChat(message.slice(0,45)||"New chat");if(!chatId)return;const history=messages.slice(-12).map(m=>({role:m.role,content:m.content}));setMessages(v=>[...v,{role:"user",content:message}]);await saveMessage(chatId,"user",message);setLoading(true);try{const r=await fetch("/api/engine",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,history})});const d=await r.json();if(!r.ok)throw new Error(d?.error||"DOG AI could not get a response.");setMessages(v=>[...v,{role:"assistant",content:d.text}]);await saveMessage(chatId,"assistant",d.text);}catch(e){const text=e instanceof Error?e.message:"DOG AI could not get a response.";setMessages(v=>[...v,{role:"assistant",content:text}]);await saveMessage(chatId,"assistant",text);}finally{setLoading(false);}};
 const inChat=messages.length>0||loading;
 return <div className={`home ${inChat?"chat-active":""}`}>
  <header className="mobile-header"><button className="menu-button" onClick={onOpenMenu} aria-label="Open menu"><Menu size={25}/></button><div className="mobile-brand">DOG AI</div><button className="mobile-profile-button" onClick={onOpenAccount} aria-label="Open account"><UserCircle2 size={25}/></button></header>
  {!inChat&&<><section className="feature-section"><button className="feature-card" onClick={()=>onNavigate("images")}><div className="feature-icon"><ImageIcon size={26}/></div><div><div className="feature-title">Image Creation</div><div className="feature-description">Generate images from text</div></div></button><button className="feature-card" onClick={()=>onNavigate("code")}><div className="feature-icon"><Code2 size={26}/></div><div><div className="feature-title">Code Builder</div><div className="feature-description">Build, debug and improve code</div></div></button></section><section className="hero-section"><div className="hero-badge"><Sparkles size={15}/> Coding-first AI workspace</div><h1>Hello, {user?.displayName?.split(" ")[0]||"there"}.<br/>What are you building?</h1><p>Ask DOG AI for code, debugging help, architecture or ideas.</p>{memoryEnabled&&<div className="memory-hint"><Brain size={16}/> Memory is on</div>}</section></>}
  {inChat&&<section className="conversation-preview"><div className="chat-toolbar"><strong>DOG AI</strong><button onClick={()=>void startChat()}><Plus size={16}/> New chat</button></div>{messages.map((m,i)=><div className={`message-bubble ${m.role}`} key={i}><div className="preview-label">{m.role==="user"?"You":"DOG AI"}</div><div className="preview-message">{m.role==="assistant"?formatText(m.content):<p>{m.content}</p>}</div>{m.role==="assistant"&&<button className="copy-response" onClick={()=>{void navigator.clipboard?.writeText(m.content);setCopied(String(i));setTimeout(()=>setCopied(null),1200)}}><Copy size={14}/> {copied===String(i)?"Copied":"Copy"}</button>}</div>)}{loading&&<div className="ai-loading"><DogLoader size={34} label="DOG AI is thinking…"/></div>}</section>}
  <section className="chat-section"><ChatInput onSend={handleSend} disabled={loading}/>{!inChat&&<div className="bottom-placeholder"><span>DOG AI • Coding + Images</span></div>}</section>
 </div>;
}
